write_files:
  - path: "/etc/systemd/system/the-app.service"
    permissions: "0644"
    content: |
      [Unit]
      Description=Application service
      After=network.target

      [Service]
      Type=simple
      ExecStart=${deployment_path}

      [Install]
      WantedBy=multi-user.target

runcmd:
  - echo "Installing prerequisites first"
  - yum install -y oracle-cloud-agent
  - echo "Launching the app"
  - systemctl enable the-app --now
  - echo "Allowing port 80 on the firewall"
  - firewall-offline-cmd --add-port=80/tcp && systemctl restart firewalld

final_message: "The system is finally up, after $UPTIME seconds"
output: { all: "| tee -a /root/cloud-init-output.log" }
